import { describe, it, expect } from 'vitest';
import {
  detectAICoAuthors,
  identifyAITool,
  hasAIIndicators,
  getAIToolDisplayName,
  calculateAIStats,
} from './ai-detection.js';

describe('AI Detection', () => {
  describe('detectAICoAuthors', () => {
    it('should detect GitHub Copilot co-author', () => {
      const message = `Add new feature

Co-Authored-By: GitHub Copilot <copilot@github.com>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(1);
      expect(result[0].tool).toBe('copilot');
      expect(result[0].name).toBe('GitHub Copilot');
    });

    it('should detect Claude co-author', () => {
      const message = `Implement authentication

Co-Authored-By: Claude <noreply@anthropic.com>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(1);
      expect(result[0].tool).toBe('claude');
    });

    it('should detect Claude Opus 4.5 co-author', () => {
      const message = `Fix bug in parser

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(1);
      expect(result[0].tool).toBe('claude');
      expect(result[0].name).toBe('Claude Opus 4.5');
    });

    it('should detect Cursor co-author', () => {
      const message = `Add tests

Co-Authored-By: Cursor <cursor@cursor.sh>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(1);
      expect(result[0].tool).toBe('cursor');
    });

    it('should detect multiple AI co-authors', () => {
      const message = `Complex feature

Co-Authored-By: GitHub Copilot <copilot@github.com>
Co-Authored-By: Claude <claude@anthropic.com>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(2);
      expect(result.map((r) => r.tool)).toContain('copilot');
      expect(result.map((r) => r.tool)).toContain('claude');
    });

    it('should not detect human co-authors', () => {
      const message = `Pair programming session

Co-Authored-By: John Doe <john@example.com>
Co-Authored-By: Jane Smith <jane@company.org>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(0);
    });

    it('should handle mixed AI and human co-authors', () => {
      const message = `Team effort

Co-Authored-By: John Doe <john@example.com>
Co-Authored-By: Claude <noreply@anthropic.com>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(1);
      expect(result[0].tool).toBe('claude');
    });

    it('should handle case insensitive matching', () => {
      const message = `Feature

CO-AUTHORED-BY: CLAUDE <NOREPLY@ANTHROPIC.COM>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(1);
      expect(result[0].tool).toBe('claude');
    });

    it('should deduplicate co-authors', () => {
      const message = `Feature

Co-Authored-By: Claude <noreply@anthropic.com>
Co-Authored-By: Claude <noreply@anthropic.com>`;

      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(1);
    });

    it('should return empty array for messages without co-authors', () => {
      const message = 'Simple commit message';
      const result = detectAICoAuthors(message);
      expect(result).toHaveLength(0);
    });
  });

  describe('identifyAITool', () => {
    it('should identify Copilot by email', () => {
      expect(identifyAITool('GitHub Copilot', 'copilot@github.com')).toBe('copilot');
    });

    it('should identify Claude by email domain', () => {
      expect(identifyAITool('Claude', 'noreply@anthropic.com')).toBe('claude');
    });

    it('should identify Claude by name', () => {
      expect(identifyAITool('Claude Sonnet', 'ai@example.com')).toBe('claude');
    });

    it('should identify Cursor', () => {
      expect(identifyAITool('Cursor', 'cursor@cursor.sh')).toBe('cursor');
    });

    it('should identify Codeium', () => {
      expect(identifyAITool('Codeium', 'ai@codeium.com')).toBe('codeium');
    });

    it('should identify Amazon Q', () => {
      expect(identifyAITool('Amazon Q', 'q@amazon.com')).toBe('amazon-q');
    });

    it('should return null for human authors', () => {
      expect(identifyAITool('John Doe', 'john@example.com')).toBe(null);
    });

    it('should identify generic AI as other', () => {
      expect(identifyAITool('AI Assistant', 'assistant@company.com')).toBe('other');
    });
  });

  describe('hasAIIndicators', () => {
    it('should detect [AI] prefix', () => {
      expect(hasAIIndicators('[AI] Add new feature')).toBe(true);
    });

    it('should detect [ai-generated] prefix', () => {
      expect(hasAIIndicators('[ai-generated] Fix bug')).toBe(true);
    });

    it('should detect "generated by" phrases', () => {
      expect(hasAIIndicators('Code generated by Copilot')).toBe(true);
      expect(hasAIIndicators('Generated by Claude')).toBe(true);
    });

    it('should return false for normal messages', () => {
      expect(hasAIIndicators('Add new feature')).toBe(false);
      expect(hasAIIndicators('Fix bug in authentication')).toBe(false);
    });
  });

  describe('getAIToolDisplayName', () => {
    it('should return display names', () => {
      expect(getAIToolDisplayName('copilot')).toBe('GitHub Copilot');
      expect(getAIToolDisplayName('claude')).toBe('Claude');
      expect(getAIToolDisplayName('cursor')).toBe('Cursor');
      expect(getAIToolDisplayName('codeium')).toBe('Codeium');
      expect(getAIToolDisplayName('amazon-q')).toBe('Amazon Q');
      expect(getAIToolDisplayName('other')).toBe('Other AI');
    });
  });

  describe('calculateAIStats', () => {
    it('should calculate correct statistics', () => {
      const commits = [
        { author: 'alice', isAIAssisted: true, aiCoAuthors: [{ name: 'Claude', email: 'claude@anthropic.com', tool: 'claude' as const }] },
        { author: 'alice', isAIAssisted: true, aiCoAuthors: [{ name: 'Claude', email: 'claude@anthropic.com', tool: 'claude' as const }] },
        { author: 'bob', isAIAssisted: false, aiCoAuthors: [] },
        { author: 'bob', isAIAssisted: true, aiCoAuthors: [{ name: 'Copilot', email: 'copilot@github.com', tool: 'copilot' as const }] },
      ];

      const stats = calculateAIStats(commits);

      expect(stats.totalCommits).toBe(4);
      expect(stats.aiAssistedCommits).toBe(3);
      expect(stats.aiRatio).toBe(0.75);
      expect(stats.byTool).toHaveLength(2);
      expect(stats.byTool.find((t) => t.tool === 'claude')?.count).toBe(2);
      expect(stats.byTool.find((t) => t.tool === 'copilot')?.count).toBe(1);
      expect(stats.byAuthor).toHaveLength(2);
      expect(stats.byAuthor.find((a) => a.author === 'alice')?.aiCommits).toBe(2);
    });

    it('should handle empty commits array', () => {
      const stats = calculateAIStats([]);
      expect(stats.totalCommits).toBe(0);
      expect(stats.aiAssistedCommits).toBe(0);
      expect(stats.aiRatio).toBe(0);
    });

    it('should handle commits with no AI', () => {
      const commits = [
        { author: 'alice', isAIAssisted: false, aiCoAuthors: [] },
        { author: 'bob', isAIAssisted: false, aiCoAuthors: [] },
      ];

      const stats = calculateAIStats(commits);
      expect(stats.aiAssistedCommits).toBe(0);
      expect(stats.aiRatio).toBe(0);
      expect(stats.byTool).toHaveLength(0);
    });
  });
});
